version: '3.8'

services:
  dvwa:
    image: vulnerables/web-dvwa:latest
    ports:
      - "8080:80"
    environment:
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: dvwa
